default: help

help:
    just --list

# Setup the environment files used by Nuxt (.nuxt directory)
setup:
    pnpm install
    pnpm nuxi prepare ./playground

# Run the app on development mode
dev:
    pnpm nuxi dev ./playground