# Default recipe of the justfile
default: help

# Show this info message
help:
  just --list

# Setup the environment of the project
setup:
    # Do nothing, only here to report to the main monorepo
    # justfile that there is no setup in this project

# Check, lint and format all files
check:
    pnpm run check

# Run the testing website
web:
    pnpm run check

# Run the Storybook
storybook:
    pnpm run storybook