default: help

help:
    just --list

# Setup the environment files used by Nuxt (.nuxt directory)
setup:
    pnpm install
    pnpm nuxi prepare

# Run the app on development mode
dev:
    pnpm nuxi dev

# Build the app for deployment
build:
    pnpm nuxi build

# Preview how the final production website will look like
preview:
    #!/usr/bin/env bash

    if [ ! -d ".output" ]; then
        gum log -sl error "The '.output' directory is missing, did you run 'just build'?"
        gum log -sl info "Remember to rebuild your site before previewing it again!"
        exit 1
    fi

    pnpm nuxi preview

