name: "Publish versionless Docker images"

concurrency:
  group: ${{ github.workflow }} 
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    paths:
      - "**/docs/**/*"
      - "docs/**/*"

jobs:
  build-and-publish-docker-image-versionless-documentation:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-nix
      with:
        github_access_token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: ./.github/actions/login-docker
      with:
        github_access_token: "${{ secrets.GITHUB_TOKEN }}"

    - run: just build-docker-image documentation/versionless
    - run: just publish-docker-image documentation/versionless