name: "Login into the Docker CLI"
description: "Login into the Docker CLI with a predefined configuration"

inputs:
  github_access_token:
    required: true
    description: "The GitHub token to use in the action"

runs:
  using: "composite"
  steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: kutu-dev
        password: ${{ inputs.github_access_token }}

    - uses: docker/setup-buildx-action@v3
