name: "Setup Nix"
description: "Install Nix, use the local cache and install the packages listed in the default devShell"

inputs:
  github_access_token:
    required: true
    description: "The GitHub token to use in the action"

runs:
  using: "composite"

  steps:
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: "${{ inputs.github_access_token }}"

    - uses: DeterminateSystems/magic-nix-cache-action@v9

    - uses: nicknovitski/nix-develop@v1
