name: "Check"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-nix
      with:
        github_access_token: "${{ secrets.GITHUB_TOKEN }}"

    - run: just setup
    - run: just check