name: "Publish to the GitHub Container registry"

on:
  workflow_dispatch:
  push:
    tags:
      - "*/v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-nix
      with:
        github_access_token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: kutu-dev
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: just build-docker-image "${{ github.ref_name }}"
    - run: just publish-docker-image "${{ github.ref_name }}"