name: "Publish to the GitHub Container registry"

env:
  REGISTRY: ghcr.io

on:
  workflow_dispatch:
  push:
    tags:
      - "*/v*.*.*"

jobs:
  check:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: nicknovitski/nix-develop@v1

    - run: just build-docker-image ${{ github.ref_name }}

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: docker push ${{ env.REGISTRY }}/wiilink/documentation