name: "Publish to the GitHub Container registry"

on:
  workflow_dispatch:
  push:
    tags:
      - "docker/*/v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-nix
      with:
        github_access_token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: ./.github/actions/setup-docker
      with:
        github_access_token: "${{ secrets.GITHUB_TOKEN }}"

    - run: just build-docker-image "${{ github.ref_name }}"
    - run: just publish-docker-image "${{ github.ref_name }}"