name: "Publish versionless documentation Docker image"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    paths:
      - "projects/documentation/**"

jobs:
  build-and-publish-docker-image-versionless-documentation:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: ./.github/actions/setup-docker
        with:
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"

      - run: ./projects/documentation/run docker build versionless
      - run: docker push ghcr.io/wiilink24/documentation:versionless