# Default recipe of the justfile
default: help

# Show this info message
help:
  just --list

# Run the testing website
web:
    pnpm run check

# Run the Storybook
storybook:
    pnpm run storybook

# Lint and format all files
check:
    pnpm run check
